apiVersion: v1
kind: ConfigMap
metadata:
  name: logout-token-configmap
  namespace: default
data:
  KEYCLOAK_URL: "https://registry-keycloak2.k-paas.org"
  KEYCLOAK_REALM: "cp-realm"
  CLIENT_ID: "cp-client"
  PORT: "3001"
  FRONTEND_URL: "http://localhost:3000"  # 프론트엔드 URL로 변경 필요