apiVersion: v1
kind: Secret
metadata:
  name: logout-token-secret
  namespace: default
type: Opaque
data:
  # BASE64로 인코딩된 값들 (실제 배포 시 변경 필요)
  CLIENT_SECRET: bmRkelZWR1c5T0M2Y2N5NlVMclNNcnpkSWxxVGR2NWg=  # nddzVVGW9OC6ccy6ULrSMrzdIlqTdv5h
  SESSION_SECRET: eW91ci1zZXNzaW9uLXNlY3JldC1rZXktaGVyZQ==      # your-session-secret-key-here