apiVersion: apps/v1
kind: Deployment
metadata:
  name: logout-token-backend
spec:
  replicas: 1  # 메모리 기반 세션 스토리지로 인한 제약
  template:
    spec:
      containers:
        - name: logout-token-backend
          env:
            - name: GIN_MODE
              value: "release"
            - name: LOG_LEVEL
              value: "info"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          readinessProbe:
            httpGet:
              path: /api/session-status
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /api/session-status
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3