apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: logout-token-backend-prod

namespace: logout-token-prod

resources:
  - ../../base

commonLabels:
  environment: prod

patchesStrategicMerge:
  - deployment-patch.yaml
  - configmap-patch.yaml

images:
  - name: logout-token-backend
    newName: registry-dev2.k-paas.org/kpaas/logout-token-sample
    newTag: latest

configMapGenerator:
  - name: logout-token-backend-config
    behavior: merge
    literals:
      - ENVIRONMENT=production
      - DEBUG=false
      - GIN_MODE=release