apiVersion: v1
kind: ConfigMap
metadata:
  name: logout-token-backend-config
data:
  KEYCLOAK_URL: "https://registry-keycloak2.k-paas.org"
  KEYCLOAK_REALM: "cp-realm"
  CLIENT_ID: "cp-client"
  PORT: "3001"
  FRONTEND_URL: "http://logout-token-frontend-dev.logout-token-dev.svc.cluster.local:8080"