apiVersion: apps/v1
kind: Deployment
metadata:
  name: logout-token-backend
spec:
  replicas: 1  # dev 환경은 1개로 제한
  template:
    spec:
      containers:
        - name: logout-token-backend
          env:
            - name: GIN_MODE
              value: "debug"
            - name: LOG_LEVEL
              value: "debug"
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "128Mi" 
              cpu: "200m"