apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: logout-token-backend-dev

namespace: default

resources:
  - ../../base

commonLabels:
  environment: dev

patchesStrategicMerge:
  - deployment-patch.yaml
  - configmap-patch.yaml

images:
  - name: logout-token-backend
    newName: registry-dev2.k-paas.org/kpaas/logout-token-sample
    newTag: feature-dev

configMapGenerator:
  - name: logout-token-backend-config
    behavior: merge
    literals:
      - ENVIRONMENT=dev
      - DEBUG=true