apiVersion: v1
kind: Service
metadata:
  name: logout-token-frontend
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: logout-token-frontend
