apiVersion: apps/v1
kind: Deployment
metadata:
  name: logout-token-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: logout-token-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: logout-token-backend
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: logout-token-backend
        image: logout-token-backend:latest
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        env:
        - name: KEYCLOAK_URL
          valueFrom:
            configMapKeyRef:
              name: logout-token-backend-config
              key: KEYCLOAK_URL
        - name: KEYCLOAK_REALM
          valueFrom:
            configMapKeyRef:
              name: logout-token-backend-config
              key: KEYCLOAK_REALM
        - name: CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: logout-token-backend-config
              key: CLIENT_ID
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: logout-token-backend-secret
              key: CLIENT_SECRET
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: logout-token-backend-secret
              key: SESSION_SECRET
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: logout-token-backend-config
              key: PORT
        - name: FRONTEND_URL
          valueFrom:
            configMapKeyRef:
              name: logout-token-backend-config
              key: FRONTEND_URL
        livenessProbe:
          httpGet:
            path: /api/session-status
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/session-status
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: false
          runAsNonRoot: true