apiVersion: v1
kind: Secret
metadata:
  name: logout-token-backend-secret
type: Opaque
data:
  CLIENT_SECRET: bmRkelZWR1c5T0M2Y2N5NlVMclNNcnpkSWxxVGR2NWg=
  SESSION_SECRET: eW91ci1zZXNzaW9uLXNlY3JldC1rZXktaGVyZQ==