apiVersion: v1
kind: Service
metadata:
  name: logout-token-backend
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: logout-token-backend