name: Backend CI/CD

on:
  push:
    branches: [dev, main, 'feature/*']
    paths: ['backend-go/**']
  pull_request:
    branches: [dev, main]
    paths: ['backend-go/**']

env:
  REGISTRY: registry-dev2.k-paas.org
  IMAGE_NAME: kpaas/logout-token-sample

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        working-directory: ./backend-go
        run: go mod download

      - name: Run tests
        working-directory: ./backend-go
        run: go test -v ./...

      - name: Run linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.8
          working-directory: ./backend-go
          args: --config .golangci.yml --timeout 5m

  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Harbor Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend-go
          file: ./backend-go/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

      - name: Update image tag in dev overlay
        if: github.ref == 'refs/heads/dev'
        run: |
          cd backend-go/k8s/overlays/dev
          IMAGE_TAG="dev-$(echo ${{ github.sha }} | cut -c1-7)"
          sed -i "s|newTag:.*|newTag: ${IMAGE_TAG}|" kustomization.yaml
          
          # Commit and push the changes
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add kustomization.yaml
          git commit -m "chore: update backend image tag to ${IMAGE_TAG}"
          git push